{% set name = "py-pde" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-pde-{{ version }}.tar.gz
  sha256: d8719a13ae040c8da4c4c4b489b8df20b128dcb47f85064da2e7ca1b7ccc4344

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=3.1
    - numba >=0.50
    - numpy >=1.18
    - python >=3.6
    - scipy >=1.4
    - sympy >=1.5
    - h5py >=2.10
    - pandas >=1.0
    - tqdm >=4.45
    - ffmpeg

test:
  imports:
    - pde
    - pde.fields
    - pde.grids
    - pde.pdes
    - pde.solvers
    - pde.storage
    - pde.visualization
    - pde.tools.numba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zwicker-group/py-pde
  summary: Python package for solving partial differential equations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - volpatto
    - david-zwicker
