{% set name = "py-pde" %}
{% set version = "0.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-pde-{{ version }}.tar.gz
  sha256: a692fdc81df9244dabb8748f9fab2eb908e22ccd8ed9b0d359e5837caf4547b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numba
    - numpy
    - python >=3.6
    - scipy
    - sympy
    - h5py
    - pandas
    - tqdm
    - ffmpeg

test:
  imports:
    - pde
    - pde.fields
    - pde.grids
    - pde.pdes
    - pde.solvers
    - pde.storage
    - pde.visualization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zwicker-group/py-pde
  summary: Python package for solving partial differential equations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - volpatto
    - david-zwicker
